spring:
  application:
    name: group9
  datasource:
    url: "jdbc:h2:mem:demo-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    driverClassName: "org.h2.Driver"
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace