name: Create Release

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:

      - uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven


      - name: Package Application
        run: mvn -B clean package


      - name: List target directory contents
        run: ls -la target


      - name: Extract Version from pom.xml
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -Ev '(^\[|Download\w+:)')
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Find JAR File
        id: find_jar
        run: |
          JAR_PATH=$(find target -name "*.jar" | head -n 1)
          echo "Found JAR at: $JAR_PATH"
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV


      - name: Check if release exists
        id: check_release
        run: |
          RELEASE_ID=$(gh api repos/${{ github.repository }}/releases | jq -r '.[] | select(.tag_name == "v${{ env.VERSION }}") | .id')
          if [ -z "$RELEASE_ID" ]; then
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
            echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV
          fi


      - name: Create GitHub Release
        if: ${{ env.RELEASE_EXISTS == 'false' }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url || 'https://api.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets?name=d2l-mock-${{ env.VERSION }}.jar' }}
          asset_path: ${{ env.JAR_PATH }}
          asset_name: d2l-mock-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
