name: Package Java Project

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  package:
    name: Package Application After Successful Build
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Package Application
        run: mvn -B clean package

      # Upload the package
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: d2l-mock
          path: target/*.jar
