name: Package Java Project

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project with Maven
      - name: Package Application
        run: mvn -B clean package

      # Step 4: List target directory contents to check if JAR is generated
      - name: List target directory contents
        run: ls -la target

      # Step 5: Extract Version from pom.xml (without removing -SNAPSHOT)
      - name: Extract Version from pom.xml
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -Ev '(^\[|Download\w+:)')
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Store the version in environment

      # Step 6: Find the JAR file dynamically
      - name: Find JAR File
        id: find_jar
        run: |
          JAR_PATH=$(find target -name "*.jar" | head -n 1)
          echo "Found JAR at: $JAR_PATH"
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV  # Store the JAR path in environment

      # Step 7: Create a GitHub Release using the extracted version (including -SNAPSHOT)
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"  # Use the extracted version for the tag, including -SNAPSHOT
          release_name: "Release v${{ env.VERSION }}"  # Name the release based on the version, including -SNAPSHOT
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Upload the JAR file to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.JAR_PATH }}  # Use the dynamically found JAR file
          asset_name: d2l-mock-${{ env.VERSION }}.jar  # Name the asset based on the version
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
