name: Package Java Project

on:
  # This workflow will only be triggered after the 'Java CI with Maven' workflow completes
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  package:
    name: Package Application After Successful Build
    runs-on: ubuntu-latest

    # Ensure this job runs only if:
    # - The event that triggered 'Java CI with Maven' was a push to the 'main' branch
    # - The 'Java CI with Maven' workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Package Application
        run: mvn -B clean package

      # Optional: Upload the package (JAR or WAR)
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: my-package
          path: target/*.jar
